#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

# Chain the parked servers. Physics stays with the default server library.
SConscript("audio/SCsub")
SConscript("camera/SCsub")
SConscript("debugger/SCsub")
SConscript("display/SCsub")
SConscript("movie_writer/SCsub")
SConscript("rendering/SCsub")
SConscript("text/SCsub")
if not env["disable_navigation_2d"]:
    SConscript("navigation_2d/SCsub")
if not env["disable_navigation_3d"]:
    SConscript("navigation_3d/SCsub")
SConscript("xr/SCsub")
