short_name = "gd"
name = "gd"
major = 4
minor = 7
patch = 2
status = "stable"
module_config = ""
website = "https://gd.progsha.com/"
docs = "4.7"
cli = "0.8.0"  # Public runtime version.
cli_status = "dev"  # Public runtime release channel.
