short_name = "gd"
name = "gd"
major = 4
minor = 7
patch = 2
status = "stable"
module_config = ""
website = "https://gd.progsha.com/"
docs = "4.7"
cli = "0.7.5"  # Public runtime version.
cli_status = "stable"  # Public runtime release channel.
