#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_gdscript = env_modules.Clone()

env_gdscript.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
    env_gdscript.add_source_files(env.modules_sources, "./editor/*.cpp")
    SConscript("editor/script_templates/SCsub")
    # The language server needs the remote-call and stream modules.
    if env["module_jsonrpc_enabled"] and env["module_websocket_enabled"]:
        env_gdscript.add_source_files(env.modules_sources, "./language_server/*.cpp")
    else:
        env_gdscript.Append(CPPDEFINES=["GDSCRIPT_NO_LSP"])
        env.Append(CPPDEFINES=["GDSCRIPT_NO_LSP"])

if env["tests"]:
    # Compile the language tests into this module.
    env_gdscript.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_gdscript.add_source_files(env.modules_sources, "./tests/*.cpp")



