#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

# Chain the parked scene directories. Physics and navigation follow their own flags.
SConscript("main/SCsub")
SConscript("gui/SCsub")
if not env["disable_3d"]:
    SConscript("3d/SCsub")
SConscript("2d/SCsub")
SConscript("animation/SCsub")
SConscript("audio/SCsub")
SConscript("resources/SCsub")
SConscript("debugger/SCsub")
SConscript("theme/SCsub")
